spring:
  thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: UTF-8
      mode: LEGACYHTML5
      cache: false
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: zzz120413
      url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true

logging:
    level:
        root: info
        com.example: debug
    file:
        path: log/myblog-dev.log
